### PR TITLE
fix(rpc): Prevent full reload when navigating to the same page

### LINKED ISSUE #560: Navigate to the same page performs a full reload
**Describe the bug**
When you are in page / and have a link to /. This performs a full reload.

**Expected behavior**
Should not do anything? Should only navigate to the top and trigger navigate events?

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #560

### CODE REVIEW

**Review by aralroca — CHANGES_REQUESTED** [review]
Thank you for your contribution! It looks good. It would be nice to add this case to the test

https://github.com/brisa-build/brisa/blob/canary/packages/brisa/src/utils/rpc/rpc-integration.test.ts

Verify that it does not go into intercept and the scroll is called when the location.href is the same as the destination.url.
Although we know that if it do it by reading the code, it is good that each new case is well covered by tests so that in the future if we refactor or change the logic, it does not break this case.

Thank you very much and welcome as a contributor @mobley-trent  🎉!

**Comment by aralroca** [comment]
Thinking about it, @mobley-trent  it should be possible to intercept and after intercepting not to make any rendering, just scroll. If it is not intercepted, it does the normal MPA navigation, which is what it is doing now (wrong). The `canIntercept` already gives `false` at the moment and causes the native navigation of the browsers instead of the SPA.

File: packages/brisa/src/utils/rpc/rpc.ts [hunk 1]
```diff
@@ -104,6 +104,12 @@ function spaNavigation(event: any) {
   // Clean render mode from imperative navigate API
   $window._xm = null;
 
+  // Prevent navigation if the destination URL is the same as the current location
+  if (event.destination.url === location.href) {
+    $window.scrollTo(0, 0);
+    return;
```
Comment (aralroca) [inline packages/brisa/src/utils/rpc/rpc.ts]: without intercept means native MPA navigation (the current behavior, full reload)

File: packages/brisa/src/utils/rpc/rpc.ts [hunk 2]
```diff
@@ -113,6 +113,12 @@ function spaNavigation(event: any) {
   ) {
     event.intercept({
       async handler() {
+        // Prevent navigation if the destination URL is the same as the current location
+        if (event.destination.url === location.href) {
```
Comment (aralroca) [inline packages/brisa/src/utils/rpc/rpc.ts]: Currently it does not enter here because [`event.canIntercept`](https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent/canIntercept) is `false` in this case, as MDN says:

> For other URL types, navigation can be intercepted if only the fragment part differs.

fragment part doesn't differs, so `canIntercept` is `false`.

To fix this probably we can create a variable outside with this `event.destination.url === location.href` condition, and check together with the `canIntercept` on the above condition, and then here to skip the fetch + diffing.

Comment (mobley-trent) [reply packages/brisa/src/utils/rpc/rpc.ts]: Have I handled the logic correctly @aralroca ?

**Review by aralroca — CHANGES_REQUESTED** [review]
Apologies for my previous comments, I was wrong. We can handle it in a simpler way without having to intercept it, simply by calling `event.preventDefault()`.

Then it would only be necessary to add this outside:

```ts
  if(event.destination.url === location.href) {
    $window.scrollTo(0, 0);
    event.preventDefault();
  }
  ```
  
  So your last commit was almost working, only was missing this `event.preventDefault();` to work properly.
  
 Without the need for the things I had told you about earlier. Better, simpler, and less JS client code for this feature.

I recommend that to test the feature and see if it works for you, you create a project with `bun create brisa` and use a token link to the Brisa repo. Now the current code is neither working because the idea of using `sameURL` variable in the condition was to applied in a different way, like `(event.navigationType !== 'replace' || sameURL)`. 

However, as we have said, all this would not be necessary now. By doing the defaultPrevent we are adding this code and intercepting it.

Any doubt feel free to ask

File: packages/brisa/src/utils/rpc/rpc-integration.test.ts [hunk 3]
```diff
@@ -437,6 +437,11 @@ describe('utils', () => {
       window._xm = null;
     });
 
+    it('should not full reload when the destination URL is the same as the current location', async () => {
+      await simulateSPANavigation('http://localhost');
+      expect(mockNavigationIntercept).toHaveBeenCalled();
```
Comment (aralroca) [inline packages/brisa/src/utils/rpc/rpc-integration.test.ts]: `mockNavigationIntercept ` should not be called now, you miss `location.href = 'https://localhost'` before simulate the SPA navigation to reproduce the condition. Feel free also to adapt the simulator to add the `preventDefault` mock and check here that the `preventDefault` is called.

To run these tests you can run this:


```sh
bun test packages/brisa/src/utils/rpc/rpc-integration.test.ts --watch
```

File: packages/brisa/src/utils/rpc/rpc-integration.test.ts [hunk 4]
```diff
@@ -395,6 +396,9 @@ describe('utils', () => {
         navigationType?: 'push' | 'replace';
       } = {},
     ) {
+      if (location.href === url) {
```
Comment (aralroca) [inline packages/brisa/src/utils/rpc/rpc-integration.test.ts]: This condition logic is already inside the RPC that we want to test. I mean adding `preventDefault` on line 420, a similar mock strategy than `mockNavigationIntercept`

Comment (mobley-trent) [reply packages/brisa/src/utils/rpc/rpc-integration.test.ts]: I tried adding `preventDefault` to the dummy `fn` event like so:

```js
    const preventDefault = mock(() => {});

    fn({
        preventDefault,
        destination: { url },
        scroll: () => {},
        ...
```

However, it seems that this does not trigger the `event.preventDefault` method. Is there something I'm missing ?

Comment (aralroca) [reply packages/brisa/src/utils/rpc/rpc-integration.test.ts]: I guess It's because inside the `simulateSPANavigation` we have this on line 408:

```js
location.href = origin;
```

We need to adapt the simulator and we should be able to pass the `locationHref` in the configuration and do something like this:

```
location.href = locationHref ?? origin;
```

Then:

```js
const url = 'http://localhost/some-page';
await simulateSPANavigation(url, { locationHref: url });
```

Probably something like that should adapt the simulator.

**Review by aralroca — APPROVED** [review]
It looks good. Thanks for contributing! 🎉
