### PR TITLE
fix(rpc): improve Server Actions register (better performance + fix bug)

### LINKED ISSUE #774: Server actions are NOT registred correctly
Actions currently register recursively with a requestAnimationFrame. This makes the performance very busy if you look at it. It would be better to use a MutableObservable together with an initial execution. Since new actions can only be registered when modifying the DOM (SPA navigation or rendering from another action).

This current behavior adds to an issue we have experienced with @AlbertSabate . The problem is that the recursion stops executing after the DOMContentLoaded, so in some cases, the actions are not registered correctly after modifying the DOM (by SPA).

### PR DESCRIPTION
**Pull request by aralroca**
Fixes https://github.com/brisa-build/brisa/issues/774

TODO:

- [x] Fix current tests
- [x] Add new test

### CODE REVIEW

File: packages/brisa/src/utils/transfer-store-service/index.ts [hunk 1]
```diff
@@ -15,7 +15,6 @@ export default async function transferStoreService(req: RequestContext) {
   const bodyAvailable = req.method === 'POST' && !req.bodyUsed;
   const isFormData = contentType?.includes('multipart/form-data');
   const formData = isFormData && bodyAvailable ? await req.formData() : null;
-  const encryptedKeys = new Set<string>();
```
Comment (aralroca) [inline packages/brisa/src/utils/transfer-store-service/index.ts:18]: Note: unused variable
