### PR TITLE
fix(build): transform brisa.config import from dynamic to static

### LINKED ISSUE #801: Transform config import from dynamic to static

### PR DESCRIPTION
**Pull request by aralroca**
Fixes https://github.com/brisa-build/brisa/issues/801
Related to https://github.com/brisa-build/brisa/issues/628

Now brisa.config is incrusted into the `build/server.js` . No more need of dynamic import for it.

### CODE REVIEW

File: packages/brisa/src/utils/attach-brisa-project-internals/index.ts [hunk 1]
```diff
@@ -20,12 +20,17 @@ export default function attachBrisaProjectInternalsPlugin() {
     ? `export { default as i18n } from '${i18nPath}';`
     : 'export const i18n = null;';
 
+  const configPath = getImportableFilepath('brisa.config', ROOT_DIR);
+  const configExport = configPath
+    ? `export { default as config } from '${configPath}';`
+    : 'export const config = null;';
```
Comment (aralroca) [inline packages/brisa/src/utils/attach-brisa-project-internals/index.ts]: instead of `null` should be an empty object (as the old default)
